### Search Vehicle Lots
POST http://localhost:8080/api/v1/vehicleLots/search
Content-Type: application/json

[
  {
    "length": 10,
    "quantity": 1
  }
]

> {%
    client.log(`List accounts response status is: ${response.status}`)
    client.test('Verify list accounts response', () => {
        client.assert(response.status === 200, 'Failed to find vehicle lots for rent.')
    })
%}

